# Generated by Django 2.0.7 on 2018-07-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlecredentials',
            name='userId',
        ),
        migrations.AlterField(
            model_name='googlecredentials',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kotouser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
