# Generated by Django 2.0.7 on 2018-07-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180730_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('transId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('isExpence', models.BooleanField(default=True)),
            ],
        ),
    ]
