# Generated by Django 2.0.7 on 2018-07-30 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='kotoUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.kotoUser'),
            preserve_default=False,
        ),
    ]
