# Generated by Django 2.0.7 on 2018-07-30 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_transaction_kotouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecredentials',
            name='kotoUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.kotoUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='googlecredentials',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
