# Generated by Django 2.0.7 on 2018-07-30 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20180730_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonString', models.CharField(max_length=1000)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.transaction')),
            ],
        ),
    ]
