# Generated by Django 2.0.7 on 2018-07-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecredentials',
            name='email',
            field=models.EmailField(max_length=500),
        ),
    ]
