# Generated by Django 2.0.7 on 2018-07-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
