# Generated by Django 2.0.7 on 2018-08-01 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20180731_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='expences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=10000)),
                ('comments', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=1000)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=10000)),
                ('comments', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=1000)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.transaction')),
            ],
        ),
    ]
