# Generated by Django 2.0.7 on 2018-08-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_expences_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expences',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
